### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by damontoro** [psimarro-g/minishell#1]
# TODO Minishell

Tareas que faltan por hacer, separadas por su categoria y con importancia del 1 al 5 

### Todo General

- Revisar la señal sigquit para que imprima algo
- [x] Makefile (5)
- [x] Incluir la libft en libs (5)
- [x] Struct general del comando (4)
- [x] Struct general de la minishell (4) [David]
- [x] Gestión de las señales (3)  (arreglar el control 4 para el heredoc)
- [x] Inicialización de estructuras y datos (como las envp y el dir actual, etc)
    - [x]  Copiar las envp
- [x] Hacer un logo bonito al iniciar la minishell (1)
- [x] Hacer el historial (3)

### Todo Parsing

- [x] Lectura del input(5)
- [x] Parseo del input (4)
  - [x] Categorización y manejo de los tokens (2)
     - [x] >
     - [x] > 
     - [x] <<
     - [x] >>
     - [x] |
     - [x] comando (problema con wc -l < infile a b )
     - [x] $envp
     - [x] Manejar bien las comillas
  - [x] Control de errores de input (2) [Pablo]
  - [ ] Manejar el wildcard (1)

- [x] Estructura de parseo (4)

### Todo Execute

- [x] Función general de execute (4)
	- [x] Implementación de las funciones nativas (3)
		- [x] Echo (2)
		- [x] cd (2)
		- [x] pwd (2)
		- [x] export (2)
		- [x] unset (2)
		- [x] env (2)
		- [x] exit (2)
	- [x] Probar los built ins
	- [x] Guardar los codigos de salida
	- [x] Implementación de la ejecución de comando simples (3)
	- [x] Implementación de las pipes (3)

### Todo Tests

- [x] Tests con permisos de archivos [pablo]
- [x] Tests sin variables de entorno
- [x] Tests funcionalidad simple
- [x] Tests borrando cosas (el directorio actual o al anterior antes de hacer cd)
- [x] Fallos de comandos y el orden en el que comprueba las cosas

**Comment by psimarro-g** [comment]
finished project
